### ISSUE TITLE
Up for PR's?

### ISSUE THREAD

**Issue by dariusc93** [digitalocean/go-libvirt#10]
Will anyone be allowed to do PR to this repo? We have used libvirt with rpc for a while (better than creating and using binding) but in a different language but thought about bringing it to Go and then I saw this and thought it would be cool to just contribute instead of doing the same thing

**Comment by dariusc93** [comment]
Ignore the issue. Overlooked the CONTRIBUTING.md.

**Comment by mdlayher** [comment]
Absolutely!  We'd love contributions from anyone with experience with the libvirt RPC protocol.  If there's a feature you'd like to add, just open an issue first with your idea and proposed changes, and we'd be happy to discuss it.

**Comment by dariusc93** [comment]
Thanks!
