### ISSUE TITLE
End of file while reading data: Input/output error

### ISSUE THREAD

**Issue by fcddk** [digitalocean/go-libvirt#100]
Cause libvirtd error：
logs: virNetSocketReadWire:1811 : End of file while reading data: Input/output error

**Comment by benlemasurier** [comment]
Can you please provide more detail? 

- What method did you call?
- Did you remember to `Close()` the connection?
- Libvirt version?
- QEMU version?
- Go version? 

A snippet of code which reproduces this problem would be great.

**Comment by benlemasurier** [comment]
closing - feel free to comment if you need additional assistance.
