### ISSUE TITLE
connect: resource temporarily unavailable

### ISSUE THREAD

**Issue by fcddk** [digitalocean/go-libvirt#101]
log: 2020-05-09T00:57:19Z E! failed to dial libvirt: dial unix /var/run/libvirt/libvirt-sock: connect: resource temporarily unavailable
2020-05-09T00:57:19Z E! failed to retry dial libvirt: dial unix /var/run/libvirt/libvirt-sock: connect: resource temporarily unavailable

**Comment by fcddk** [comment]
code:
`	//connect
	conn, err := net.DialTimeout("unix", ag.SockUrl, ag.ConnectTimeout*time.Second-time.Millisecond*100)
	if err != nil {
		log.Printf("E! failed to dial libvirt: %s", err.Error())
		//retry
		time.Sleep(10 * time.Millisecond)
		conn, err = net.DialTimeout("unix", ag.SockUrl, ag.ConnectTimeout*time.Second-time.Millisecond*100)
		if err != nil {
			log.Printf("E! failed to retry dial libvirt: %s", err.Error())
			return
		}
	}
	defer conn.Close()`

**Comment by trapgate** [comment]
This has nothing to do with go-libvirt, and your sample code works fine for me.

**Comment by benlemasurier** [comment]
closing; looks like an issue with the underlying libvirt daemon. Please ensure:

* libvirtd is running
* libvirtd is configured to listen for local socket connections
* you have the proper permissions for `/var/run/libvirt/libvirt-sock`
