### ISSUE TITLE
Do not use this digitalocean!

### ISSUE THREAD

**Issue by Vendin** [digitalocean/go-libvirt#102]
Hi.
I have been waiting for VPC functional for several weeks. https://github.com/terraform-providers/terraform-provider-digitalocean/issues/415
When it was added, I immediately used it in my project.
And Digitalocean blocked my account without explaining the reasons and did not tell me anything.
I lost work on which I worked for several weeks.
I urge everyone to use anything AWS, GCP, Azure, but not this garbage ocean.
Digitalocean doesn't care about its customers!

**Comment by oneumyvakin** [comment]
Hi @Vending

I can understand you that it's hurt when we lose results of our work, but what you achieve now it's only demotivation of DigitalOcean employees which are maintain this repository. 
Try to find right communication channel with DigitalOcean and describe your case.

**Comment by Vendin** [comment]
@oneumyvakin 
Maybe I'm not demotivating employees, but I’ll open their eyes to the company in which they work, that this company does not care about customers, and that it’s better not to work in such a campaign.

Of course, I have been talking with support for 10 days, I have 2 tickets open (screenshot below), but they either ignore me or answer me with a template phrase. They do not want to help me.

And this is not my personal opinion, it is full of negative reviews about the digital ocean at various forums and platforms.
https://hostadvice.com/hosting-company/digital-ocean-reviews/
https://trustpilot.com/review/digitalocean.com

Here you can read about the connection of the digital ocean with crime and piracy.
https://trustpilot.com/reviews/5e9975a1086b640954390db8
https://trustpilot.com/reviews/5cbc0adea8436908c40ccc82
https://trustpilot.com/reviews/5cb42a01a8436908c409ff07

We must not tolerate humiliation.
