### ISSUE TITLE
failed to get DomainBlockStats: invalid argument: invalid path: vdl

### ISSUE THREAD

**Issue by fcddk** [digitalocean/go-libvirt#103]
libvirt version: 4.0.0
go-libvrit version: v0.0.0

code: 
`	// Report block device statistics. storage
	for _, disk := range libvirtSchema.Devices.Disks {
		if disk.Device == "cdrom" || disk.Device == "fd" {
			continue
		}

		isActive, err := l.DomainIsActive(*domain)
		if err != nil {
			log.Printf("E! [domain:%s] failed to get domain active state for block: %s", domain.Name, err.Error())
			return err
		}
		var rRdReq, rRdBytes, rWrReq, rWrBytes int64
		if isActive == 1 {
			rRdReq, rRdBytes, rWrReq, rWrBytes, _, err = l.DomainBlockStats(*domain, disk.Target.Device)
			if err != nil {
				log.Printf("E! [domain:%s] failed to get DomainBlockStats: %v", domain.Name, err.Error())
				return err
			}`

**Comment by fcddk** [comment]
log:
E! [domain:instance-00008e2a] failed to get DomainBlockStats: invalid argument: invalid path: vdl
E! [domain:instance-00008e2a] failed to get DomainBlockStats: invalid argument: invalid path: vdn
E! [domain:instance-00008e2a] failed to get DomainBlockStats: invalid argument: invalid path: vdm

**Comment by trapgate** [comment]
Can you explain why you think this is a problem with go-libvirt?

**Comment by fcddk** [comment]
This kind of log seems to be caused by the absence of path when libvirt queries the monitoring data, but it is obviously not a good phenomenon to output error logs frequently. Mainly want a way to avoid this result, if the solution exists.

**Comment by trapgate** [comment]
Libvirt is telling you that your vm doesn't have devices vdl, vdn, and vdm. I don't see a problem with go-libvirt here.
