### ISSUE TITLE
failed to get DomainInterfaceStats: invalid argument: 'tap2c714c60-c8' is not a known interface

### ISSUE THREAD

**Issue by fcddk** [digitalocean/go-libvirt#104]
libvirt version: 4.0.0
go-libvrit version: v0.0.0

code:
`	
// Report network interface statistics. 网络

	for _, iface := range libvirtSchema.Devices.Interfaces {
		if iface.Target.Device == "" {
			continue
		}

		isActive, err := l.DomainIsActive(*domain)
		if err != nil {
			log.Printf("E! [domain:%s] failed to get domain active state for interface: %s", domain.Name, err.Error())
			return err
		}

		var rRxBytes, rRxPackets, rRxErrs, rRxDrop, rTxBytes, rTxPackets, rTxErrs, rTxDrop int64

		if isActive == 1 {
			rRxBytes, rRxPackets, rRxErrs, rRxDrop, rTxBytes, rTxPackets, rTxErrs, rTxDrop, err = l.DomainInterfaceStats(*domain, iface.Target.Device)

			if err != nil {
				log.Printf("E! [domain:%s] failed to get DomainInterfaceStats: %s", domain.Name, err.Error())
				return err
			}`

**Comment by fcddk** [comment]
log：
E! [domain:instance-00007f3c] failed to get DomainInterfaceStats: invalid argument: 'tap2c714c60-c8' is not a known interface
E! [domain:instance-00008e2a] failed to get DomainInterfaceStats: invalid argument: 'tap63df1d05-99' is not a known interface

**Comment by trapgate** [comment]
Again, I don't see a go-libvirt problem here.
