### ISSUE TITLE
get monitor data timeout 

### ISSUE THREAD

**Issue by fcddk** [digitalocean/go-libvirt#105]
It is found that the problematic virtual machine monitoring data is stuck, and the response is not obtained for a long time.

log:  Guest agent is not responding.

**Comment by fcddk** [comment]
Why there is no timeout control？
l.DomainGetInfo(*domain)
l.DomainBlockStats(*domain, disk.Target.Device)
l.DomainInterfaceStats(*domain, iface.Target.Device)

**Comment by connorkuehl** [comment]
I've filed #182 to make this suggestion more broadly applicable to the entire go-libvirt API. Thank you!
