### ISSUE TITLE
connect resource cannot be released

### ISSUE THREAD

**Issue by fcddk** [digitalocean/go-libvirt#106]
libvirt log :
<30>2020-06-11T08:42:47.577912+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.489+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.581094+08:00 cmp001 libvirtd[18541]: message repeated 95 times: [ 2020-06-11 00:42:47.489+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.581120+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.490+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.584284+08:00 cmp001 libvirtd[18541]: message repeated 98 times: [ 2020-06-11 00:42:47.490+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.584310+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.491+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.586997+08:00 cmp001 libvirtd[18541]: message repeated 91 times: [ 2020-06-11 00:42:47.491+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.587023+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.492+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.590406+08:00 cmp001 libvirtd[18541]: message repeated 98 times: [ 2020-06-11 00:42:47.492+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.590467+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.493+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.593430+08:00 cmp001 libvirtd[18541]: message repeated 94 times: [ 2020-06-11 00:42:47.493+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.593456+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.494+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.596393+08:00 cmp001 libvirtd[18541]: message repeated 87 times: [ 2020-06-11 00:42:47.494+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.596419+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.495+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.598657+08:00 cmp001 libvirtd[18541]: message repeated 71 times: [ 2020-06-11 00:42:47.495+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.598683+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.496+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.600824+08:00 cmp001 libvirtd[18541]: message repeated 71 times: [ 2020-06-11 00:42:47.496+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.600885+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.497+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.603485+08:00 cmp001 libvirtd[18541]: message repeated 83 times: [ 2020-06-11 00:42:47.497+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.603511+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.498+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.606121+08:00 cmp001 libvirtd[18541]: message repeated 87 times: [ 2020-06-11 00:42:47.498+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.606142+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.499+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.608683+08:00 cmp001 libvirtd[18541]: message repeated 106 times: [ 2020-06-11 00:42:47.499+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.608710+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.500+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.610636+08:00 cmp001 libvirtd[18541]: message repeated 74 times: [ 2020-06-11 00:42:47.500+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.610669+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.501+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.613128+08:00 cmp001 libvirtd[18541]: message repeated 100 times: [ 2020-06-11 00:42:47.501+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.613154+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.502+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.615599+08:00 cmp001 libvirtd[18541]: message repeated 98 times: [ 2020-06-11 00:42:47.502+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.615626+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.503+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.617977+08:00 cmp001 libvirtd[18541]: message repeated 91 times: [ 2020-06-11 00:42:47.503+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.617996+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.504+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.620380+08:00 cmp001 libvirtd[18541]: message repeated 93 times: [ 2020-06-11 00:42:47.504+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.620400+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.505+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.622342+08:00 cmp001 libvirtd[18541]: message repeated 76 times: [ 2020-06-11 00:42:47.505+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.622369+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.506+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.624397+08:00 cmp001 libvirtd[18541]: message repeated 82 times: [ 2020-06-11 00:42:47.506+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.624425+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.507+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.626356+08:00 cmp001 libvirtd[18541]: message repeated 85 times: [ 2020-06-11 00:42:47.507+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.626376+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.508+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.628627+08:00 cmp001 libvirtd[18541]: message repeated 88 times: [ 2020-06-11 00:42:47.508+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.628647+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.509+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.630766+08:00 cmp001 libvirtd[18541]: message repeated 99 times: [ 2020-06-11 00:42:47.509+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]
<30>2020-06-11T08:42:47.630785+08:00 cmp001 libvirtd[18541]: 2020-06-11 00:42:47.510+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error
<30>2020-06-11T08:42:47.632915+08:00 cmp001 libvirtd[18541]: message repeated 78 times: [ 2020-06-11 00:42:47.510+0000: 18541: error : virNetSocketReadWire:1811 : End of file while reading data: Input/output error]

Bugs caused:
In my monitoring collector program, there will be stuck, when encountering the above situation in libvirt.

**Comment by trapgate** [comment]
I have the same question about this that I have asked about several of your previous bugs: please explain why you think this is related to go-libvirt. As far as I can tell, you're getting errors back from libvirtd when calling NetSocketReadWire. That doesn't suggest a bug in go-libvirt.

**Comment by fcddk** [comment]
These errors are indeed exceptions generated by libvirt, but go-libvirt seems to be not robust enough to handle these exceptions and is often fatal during use, because I cannot release connection resources and cannot control my app, especially timeout .

**Comment by trapgate** [comment]
Your code seems to have called NetSocketReadWire and received an error. go-libvirt doesn't handle errors, it just reports them to the caller. I don't understand what you mean by "I cannot release connection resources".

It's true that go-libvirt doesn't currently accept contexts, which would allow the caller to control timeouts, but you can work around that with a channel and a goroutine.
