### ISSUE TITLE
Allow to specify libvirt driver URI to connect to

### ISSUE THREAD

**Issue by baez90** [digitalocean/go-libvirt#116]
First of all: I really appreciate all your efforts to get a libvirt integration without C bindings!

Currently the `Connect() error` method uses the hardcoded libvirt driver URI `qemu:///system` which is kind of a showstopper for projects where I'd like to use this library.

After playing around a bit with the code I could not notice any problem with adding an overload like

`ConnectToURI(uri string) error` that allows for instance to use the mock driver `test:///default` or other libvirt drivers.

I'll open a PR and would be happy about any feedback!

Kind regards
Peter

**Comment by benlemasurier** [comment]
I'm fine with the API changing, updating `Connect()` to `Connect(uri string)`. Including an exported `const`, such as `DefaultConnectURI = qemu://system` might also be a good idea.

**Comment by baez90** [comment]
Fine for me, too.
I just thought keeping the original API isn't that bad and is not so much overhead.

I just opened the PR, just let me know if I should change it!
