### ISSUE TITLE
Make error public, to allow more fine grained control for clients

### ISSUE THREAD

**Issue by MalloZup** [digitalocean/go-libvirt#121]
This issue is a followup from: https://github.com/digitalocean/go-libvirt/issues/56

We are evaluating to use `go-libvirt` library in the upstream https://github.com/dmacvicar/terraform-provider-libvirt/pull/813

Right now, not having acess to specific error is problematic, since we leveraged these errors with the other `libvirt` golang 
library. see 

Is any chance to expose this errors? What is the valid rationale? we would be able to help to improve the library if needed.

I still agree also with @rmohr https://github.com/digitalocean/go-libvirt/issues/56#issuecomment-356212381

see for example:

https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/volume.go#L22

**Comment by MalloZup** [comment]
@trapgate what are your thoughts about this? TIA :sunflower:

**Comment by trapgate** [comment]
I agree that go-libvirt needs a public error representation. Probably the best way to get there is to re-open @rmohr's PR and update it as a starting point. Despite my misgivings at the time, I think that PR is close to what we need. I do want to be careful what gets added to the public API - for example, the current `libvirtError` struct includes a Padding field that shouldn't be in the public error; and the Code and Level fields should be a type defined in go-libvirt, not uint32.

**Comment by MalloZup** [comment]
make sense great thx @trapgate  we will be happy to expose such constructs with your feedback and guidance. ! thx

**Comment by dmacvicar** [comment]
I think this one can be closed after https://github.com/digitalocean/go-libvirt/pull/125 was merged.
