### ISSUE TITLE
Support for connection URIs

### ISSUE THREAD

**Issue by dmacvicar** [digitalocean/go-libvirt#139]
As part of integrating go-libvirt into terraform-provider-libvirt, I [have implemented](https://github.com/dmacvicar/terraform-provider-libvirt/pull/813/commits/1a86985cac99cc623a0a123f36df475f9b861991) support for connection URIs, including the tcp, tls, unix and ssh transports.

I think this could make go-libvirt easier to use for those using the original bindings, and probably belongs outside of the terraform provider.

Is there interest in having this functionality in go-libvirt?. If that is the case, I could merge the type with [go-libvirt](https://github.com/digitalocean/go-libvirt/blob/master/libvirt.go#L44) and work on a patch.

Looking forward for your feedback. //cc @trapgate

**Comment by trapgate** [comment]
I think that would be a really good addition. Connecting to libvirt has been a source of confusion for users of go-libvirt in the past; making that process more friendly would make the library easier to use.

You may run into this, by the way: https://github.com/digitalocean/go-libvirt/issues/89. We closed that bug because the problem looked like it was upstream, but I don't know if anyone ever pursued it to its source.

**Comment by JenniGriesmann** [comment]
Also somewhat tangential, but related, I have a local branch sitting around where I started having the client provide a Dialer instead of something already connected, and in there I included a couple Dialer implementations for tcp and unix.

**Comment by dmacvicar** [comment]
Thanks @JenniGriesman! That sounds good. Now I have Dial() in the URI. If you want to share the branch or some example API code I may use it as inspiration.

**Comment by JenniGriesmann** [comment]
Sorry for the slow response... I have a branch (that currently is written in a way that breaks the external API) that I rebased just now to get it up to date here:  https://github.com/digitalocean/go-libvirt/tree/jenni/take_dialer_as_input

**Comment by gidoBOSSftw5731** [comment]
Any updates on this thread? It's been a year but it looks like it could(tm) be useful?

**Comment by cfergeau** [comment]
> You may run into this, by the way: #89. We closed that bug because the problem looked like it was upstream, but I don't know if anyone ever pursued it to its source.

Fwiw, there is now an explanation for #89 : https://github.com/digitalocean/go-libvirt/issues/89#issuecomment-1607300636
