### ISSUE TITLE
libvirt: reporting the current state of the domain

### ISSUE THREAD

**Issue by simar7** [digitalocean/go-libvirt#14]
Hello,

Awesome work on this new project so far! I was wondering if it would be possible to add the the current domain state in the info that can be accessed? I'm willing to work on this but just need to know where to start poking. 

It seems like that we could use the `REMOTE_PROC_DOMAIN_GET_STATE = 212
` remote event as highlighted in this [doc](https://libvirt.org/git/?p=libvirt.git;a=blob_plain;f=src/remote/remote_protocol.x;hb=HEAD).

**Comment by benlemasurier** [comment]
Absolutely, we're happy to receive pull requests and you're on the right track. `REMOTE_PROC_DOMAIN_GET_STATE = 212` is the correct call to receive domain state. You'll need to first make a call too `lookup()` to obtain the domain, and then pass it along with your call to `ProcDomainGetState`. Building libvirt with the wireshark libvirt dissector is very useful for debugging. 

Good luck!

**Comment by mdlayher** [comment]
Reopening this issue to track it, until a PR is merged.  @simar7 , feel free to ping if you get stuck!

**Comment by mdlayher** [comment]
@simar7 we just created `#go-qemu` on freenode if you're interested in joining us on IRC to discuss this more!

**Comment by simar7** [comment]
Thanks guys, will look into this soon.

**Comment by nemca** [comment]
Current state of the domen should be a part of struct `Domain` or separate method, like:
```
func (l *Libvirt) DomainState(dom string) (string, error)
```
?

**Comment by benlemasurier** [comment]
@nemca Yeah, the latter. The current convention is to have methods on the `Libvirt` type.

**Comment by nemca** [comment]
This issue may be closed. [merged PR](https://github.com/digitalocean/go-libvirt/pull/23)
