### ISSUE TITLE
Tunnel via SSH?

### ISSUE THREAD

**Issue by johnnybubonic** [digitalocean/go-libvirt#143]
Since #140 was implemented and `New()` deprecated, how is one supposed to do a `qemu+ssh` connection?

I was under the impression this should work:

```
package main

import (
	"fmt"

	"github.com/digitalocean/go-libvirt"
	`github.com/digitalocean/go-libvirt/socket`
	`github.com/digitalocean/go-libvirt/socket/dialers`
)

func main() {

	var conn *libvirt.Libvirt
	var dialer socket.Dialer
	var err error

	dialer = dialers.NewRemote("<IP_ADDRESS_HERE>", dialers.UsePort("22"))

	conn = libvirt.NewWithDialer(dialer)
	if err = conn.ConnectToURI("qemu+ssh://user@<IP_ADDRESS_HERE>/system"); err != nil {
		fmt.Println(err)
		return
	}
}
```

But it just hangs.

I find it hard to believe SSH tunneling was broken by oversight considering it's treated as a first-class connection URI upstream.

**Comment by trapgate** [comment]
Have a look at #89, you may be running into the same problem.

**Comment by JenniGriesmann** [comment]
Assuming that's the issue, I think you could potentially work around it by implementing your own dialer instead of using the pre-fab "remote" one.

**Comment by LordNoteworthy** [comment]
I am having a similar issue, the error returned by libvirt server is: `"msg":"failed to run the server: procedure interrupted while awaiting response"`.

I am using `ssh` as transport connection, with a passwordless ssh key pair.

```go
dialer := dialers.NewRemote(address, dialers.UsePort(port))
conn = libvirt.NewWithDialer(dialer)
uri := fmt.Sprintf("qemu+ssh://%s@%s/system?keyfile=id_rsa&no_tty=1", user, address)
err = conn.ConnectToURI(libvirt.ConnectURI(uri))
```
