### ISSUE TITLE
ci: remove scripts/golint.sh, replace with built-in golint flag

### ISSUE THREAD

**Issue by mdlayher** [digitalocean/go-libvirt#16]
`golint` has a flag that causes it to exit with non-zero status, rendering our CI build script for this purpose obsolete.

Replace with `golint -set_exit_status ./...` in CI.

This is an easy Hacktoberfest contribution, so I'll leave this unfixed for a few days.  Feel free to submit a PR to fix this and work toward that t-shirt!

**Comment by mdlayher** [comment]
Closed by #17 .

**Comment by micoratih** [comment]
#17
