### ISSUE TITLE
Are events possible with this pure-go RPC method?

### ISSUE THREAD

**Issue by purpleidea** [digitalocean/go-libvirt#21]
Will we be able to receive events when states change? Is this possible either now or with the RPC?

Thanks

**Comment by benlemasurier** [comment]
Hey @purpleidea,

I'm not sure I fully understand your question.  We do have support for domain events, see [libvirt.Events](https://github.com/digitalocean/go-libvirt/blob/master/libvirt.go#L225). Is that what you're looking for?

**Comment by purpleidea** [comment]
PS: I was investigating this in the context of https://github.com/purpleidea/mgmt/ -- If you're interested, please let me know!

**Comment by mdlayher** [comment]
Very cool @purpleidea .  Is the intent to replace the cgo package with our Go one?

**Comment by vinzenz** [comment]
@mdlayher yes and I am actually in the process of adding also SASL support to this one, at least preliminary

**Comment by mdlayher** [comment]
@vinzenz Neat!  We are happy to accept PRs for any libvirt RPC functionality.  Feel free to join us on IRC too!  #go-qemu at freenode.
