### ISSUE TITLE
Define new domain

### ISSUE THREAD

**Issue by nemca** [digitalocean/go-libvirt#25]
How plans define the domain?
Can I implement methods `DomainDefineXML(xml []byte) error` and `DomainDefineXMLFlags(xml []byte, flags DomainDefineFlags) error` like [libvirt documentation](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainDefineXML)

**Comment by manny-ortiz** [comment]
Nice I was just asking about this last week.  Was going to look at adding it after I wrapped up another project.

**Comment by nemca** [comment]
This issue may be closed. [merged PR](https://github.com/digitalocean/go-libvirt/pull/26)
