### ISSUE TITLE
Obtain amount of memory currently used by the domain

### ISSUE THREAD

**Issue by amandahla** [digitalocean/go-libvirt#38]
I would like to obtain the amount of memory currently used by the domain like [here](http://libvirt.org/docs/libvirt-appdev-guide-python/en-US/html/libvirt_application_development_guide_using_python-Guest_Domains-Monitoring-Memory.html
)

I'll try to implement REMOTE_PROC_DOMAIN_MEMORY_STATS, ok? What do you think? :-)

**Comment by trapgate** [comment]
Fixed by Ben's commit of Amanda's implementation, and also present in the new generated code. Closing.
