### ISSUE TITLE
Obtain statistics about domains

### ISSUE THREAD

**Issue by amandahla** [digitalocean/go-libvirt#40]
Like command:
virsh domstats domainName

From [remote_protocol.x](https://libvirt.org/git/?p=libvirt.git;a=blob_plain;f=src/remote/remote_protocol.x;hb=HEAD)
 REMOTE_PROC_CONNECT_GET_ALL_DOMAIN_STATS = 344

**Comment by trapgate** [comment]
This is addressed in deb7a54ff8b8a5bdeb4faa8f555e9a7394eb5948; the entry point would be ConnectGetAllDomainStats()
