### ISSUE TITLE
Use d-bus instead of RPC?

### ISSUE THREAD

**Issue by vtolstov** [digitalocean/go-libvirt#68]
Does you plan provide support from digitalocean to this package or after some times  move to dbus based? (i think you know that libvirt devs write dbus interface to libvirt and in this case this generated wire binding can be relaced with dbus based)

**Comment by trapgate** [comment]
We don't have any plans to do that at the moment, and we haven't investigated to see what would be gained. I'd be curious to see whether this simplified the go binding generator, but there's nothing urgent pushing us in this direction right now.

**Comment by vtolstov** [comment]
thanks!
