### ISSUE TITLE
Is there places where I can put key,cert and ca for mtls?

### ISSUE THREAD

**Issue by hunkeelin** [digitalocean/go-libvirt#75]
I am trying to migrate via qemu+tls. For virsh it's `virsh migrate --live testvm qemu+tls://$destination/system` where the client will read from `/etc/pki/libvirt/clientcert.pem` `/etc/pki/libvirt/private/clientkey.pem` and `/etc/pki/CA/cacert.pem`

I see no fields where I can put the key/crt/ca in `[]byte` in the this library. is it implemented? 

https://godoc.org/github.com/digitalocean/go-libvirt

**Comment by trapgate** [comment]
I think you want to look at DomainMigrate3, where you can provide a connection to the destination host as part of the call. You can also look at the virsh sources to see how it builds its connection objects when certs are used.

**Comment by hunkeelin** [comment]
Yes you can provide the connection via the following: 

`	dconnuri := []string{"qemu+tls://foo/system"}
	if _, err := l.DomainMigratePerform3Params(dom, dconnuri,
		[]TypedParam{}, []byte{}, flags); err != nil {
		t.Fatalf("unexpected live migration error: %v", err)
	}`

I can specify the string to be `qemu+tls`. However, I am having a disconnection on where to put the key,cert and ca information for mtls to work. in `virsh`, it will read the the keys,cert and ca.pem in the locations i specifiy on OP automatically.

**Comment by trapgate** [comment]
The code that reads the cert and key from disk is part of virsh, not libvirt's rpc interface. It would be possible to add such a thing to go-libvirt as a convenience function, but it doesn't exist today. I'm going to close this issue, but if you want to file a PR for this work, you can reopen it for discussion.
