### ISSUE TITLE
StorageVolUpload corrupts image

### ISSUE THREAD

**Issue by dsbrng25b** [digitalocean/go-libvirt#82]
I try to upload a Ubuntu image to libvirt via StorageVolUpload. If I upload the image from a file it does work but if I upload it from a http stream the image gets corrupted.
Strangely it does work from http stream as well if I use a big buffered reader in between.
Does anyone have an idea whats going on here?

Here are the steps to reproduce the behaviour:
* download the image
```
curl -O https://cloud-images.ubuntu.com/minimal/releases/disco/release-20190605/ubuntu-19.04-minimal-cloudimg-amd64.img
```

* download test code [main.txt](https://github.com/digitalocean/go-libvirt/files/3311212/main.txt)
```
curl -o main.go https://github.com/digitalocean/go-libvirt/files/3311212/main.txt
```

* run test
```
go run main.go
```

* compare downloaded files in /var/lib/libvirt/images (or where ever your default pool stores the files)
```
sha256sum /var/lib/libvirt/images/image_from_*
```

**Comment by trapgate** [comment]
The actual size of that image file (https://cloud-images.ubuntu.com/minimal/releases/disco/release-20190605/ubuntu-19.04-minimal-cloudimg-amd64.img) is 155MB, so for your test that uses a large buffered reader, the image will fit completely in the reader's buffer. I suspect that's a clue. Can you try this test without using the progress bar's ProxyReader? I'm wondering if that code has a bug that causes it to report that the transfer is complete, when it actually isn't.

**Comment by dsbrng25b** [comment]
@trapgate thank you for your answer. That was also my first guess, but the ProxyReader does not cause the problem. The same problem appears without progress bar. 
To check if StorageVolUpload consumes all data from the reader I used the CountReader in my example. The number of bytes read from the http stream and from the file are the same. However, in the end the image from http has a smaller size in /var/lib/libvirt/images. 
```
-rw------- 1 root root 162529280 20. Jun 21:38 /var/lib/libvirt/images/image_from_file
-rw------- 1 root root 162512896 20. Jun 21:39 /var/lib/libvirt/images/image_from_http
```
To me it looks that something is not properly flushed in the end.

**Comment by vtolstov** [comment]
@dsbrng25b do you run Flush method and check error from it and from Close method?

**Comment by dsbrng25b** [comment]
@vtolstov I used `defer resp.Body.Close()` for the http stream.  Now I moved the resp.Body.Close() before the ConnectClose and checked for errors but it does not return an error. 
Which Flush method do you mean? As far as I understand a Flush or Close method is not required because the StorageVolUpload accepts an io.Reader. So to my understanding StorageVolUpload should Read until io.EOF.

**Comment by dsbrng25b** [comment]
I found the problem. The sendStream function does not return remaining bytes on io.EOF (see #83).
