### ISSUE TITLE
telegraf libvirt plugin crashes in rpc.go for some VMs

### ISSUE THREAD

**Issue by ahothan** [digitalocean/go-libvirt#85]
Here is the back trace:

Jul  6 09:35:00 CVIM-compute-1 telegraf: panic: runtime error: makeslice: len out of range
Jul  6 09:35:00 CVIM-compute-1 telegraf: goroutine 189 [running]:
Jul  6 09:35:00 CVIM-compute-1 telegraf: github.com/influxdata/telegraf/vendor/github.com/digitalocean/go-libvirt.(*Libvirt).listen(0xc42073c230)
Jul  6 09:35:00 CVIM-compute-1 telegraf: /builddir/build/src/github.com/influxdata/telegraf/vendor/github.com/digitalocean/go-libvirt/rpc.go:179 +0xb9
Jul  6 09:35:00 CVIM-compute-1 telegraf: created by github.com/influxdata/telegraf/vendor/github.com/digitalocean/go-libvirt.New
Jul  6 09:35:00 CVIM-compute-1 telegraf: /builddir/build/src/github.com/influxdata/telegraf/vendor/github.com/digitalocean/go-libvirt/libvirt.go:549 +0x25d
Jul  6 09:35:00 CVIM-compute-1 systemd: telegraf.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jul  6 09:35:00 CVIM-compute-1 systemd: Unit telegraf.service entered failed state.

This only happens for some VMs and not other VMs.

**Comment by benlemasurier** [comment]
Fixed by PR #86
