### ISSUE TITLE
NetworkUpdate: Operation not supported: can't update 'ip' section of network 'default'

### ISSUE THREAD

**Issue by a2geek** [digitalocean/go-libvirt#87]
I'm not entirely certain if this is a bug in my code or something is up with the NetworkUpdate call from this library. 

I'm writing some code that will ultimately be installed into a VM in order to manage multiple VM's. The base OS layer does not have any libvirt dependencies, and this is the best solution for my needs. (So thanks for that!)

When I do a NetworkUpdate to add an IP>DHCP>Host entry, an error is generated: `Operation not supported: can't update 'ip' section of network 'default'`.

What I've done:
* verified the project is on the latest code.
* extracted the specific code, and it fails.
* used TLS connections (thinking there may be a different socket file to utilize)
* implemented with the `libvirt/libvirt-go` library, and it works.
* verified this also works from the `virsh` command-line.  

Therefore, I think I've got a valid setup but haven't been able to identify what may be wrong (in either code base).

Running on Ubuntu 18.04.2.

```
$ virsh version
Compiled against library: libvirt 4.0.0
Using library: libvirt 4.0.0
Using API: QEMU 4.0.0
Running hypervisor: QEMU 2.11.1
```
Using this library (and it fails):
```
const networkDhcpXML = "<host name='vm-8029d8c8-ee6c-45b9-6476-3ba7381c3cb5' ip='192.168.123.7'/>"
const networkName = "default"
const socket = "/var/run/libvirt/libvirt-sock"

func main() {
	conn, err := net.DialTimeout("unix", socket, 2*time.Second)
	defer conn.Close()
	if err != nil {
		panic(err)
	}
	fmt.Printf("Connected to '%s'\n", socket)

	client := libvirt.New(conn)
	err = client.Connect()
	if err != nil {
		panic(err)
	}
	fmt.Printf("Connected to libvirt\n")

	net, err := client.NetworkLookupByName(networkName)
	if err != nil {
		panic(err)
	}
	fmt.Printf("net = %v\n", net)

	xmlDesc, err := client.NetworkGetXMLDesc(net, 0)
	if err != nil {
		panic(err)
	}
	fmt.Printf("networkXMLDesc=%s\n", xmlDesc)

	cmd := uint32(libvirt.NetworkUpdateCommandAddLast)
	section := uint32(libvirt.NetworkSectionIPDhcpHost)
	//netflags := libvirt.NetworkUpdateAffectLive | libvirt.NetworkUpdateAffectConfig
	fmt.Printf("NetworkUpdate(%v, %d, %d, -1, %s, %d)\n", net, cmd, section, networkDhcpXML, 0)
	err = client.NetworkUpdate(net, cmd, section, -1, networkDhcpXML, 0)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Setup network DHCP\n")
}
```

Using the `libvirt/libvirt-go` library (and it works):
```
const networkDhcpXML = "<host name='vm-8029d8c8-ee6c-45b9-6476-3ba7381c3cb5' ip='192.168.123.7'/>"
const networkName = "default"

func main() {
	conn, err := libvirt.NewConnect("qemu:///system")
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	net, err := conn.LookupNetworkByName(networkName)
	defer net.Free()
	if err != nil {
		panic(err)
	}
	fmt.Printf("net = %v\n", net)

	xmlDesc, err := net.GetXMLDesc(0)
	if err != nil {
		panic(err)
	}
	fmt.Printf("networkXMLDesc=%s\n", xmlDesc)

	cmd := libvirt.NETWORK_UPDATE_COMMAND_ADD_LAST
	section := libvirt.NETWORK_SECTION_IP_DHCP_HOST
	//netflags := libvirt.NetworkUpdateAffectLive | libvirt.NetworkUpdateAffectConfig
	fmt.Printf("NetworkUpdate(%v, %d, %d, -1, %s, %d)\n", net, cmd, section, networkDhcpXML, 0)
	err = net.Update(cmd, section, -1, networkDhcpXML, 0)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Setup network DHCP\n")
}
```

Using `virsh`:
```
$ virsh net-update default add --section ip-dhcp-host --xml "<host name='vm-8029d8c8-ee6c-45b9-6476-3ba7381c3cb5' ip='192.168.123.7'/>"
Updated network default live state
```

If it's useful, the specific usage is in the `libvirtManager` [here](https://github.com/a2geek/libvirt-bosh-cpi/blob/master/src/libvirt-bosh-cpi/mgr/libvirt.go#L323). It's been rejiggered into the samples to work out whatever issue is occurring.

Thanks for any information you may provide!

**Comment by trapgate** [comment]
The error you're getting seems to be coming from `virNetworkDefUpdateIP` in the libvirt sources. But that's not the right routine - you're trying to update the DHCP host settings, which is section "ip/dhcp/host", and is handled by `virNetworkDefUpdateIPDHCPHost`. You'd get this error if the `section` parameter passed into the `NetworkUpdate` call were wrong (3 instead of 4), but `libvirt.NetworkSectionIpDhcpHost` and `NETWORK_SECTION_IP_DHCP_HOST` are both 4, in the sources I'm looking at. (libvirt 4.0.0). It might be interesting to try some other values for the `section` parameter, and see if you get back sensible errors.

**Comment by a2geek** [comment]
I get the same response regardless of values (tried 1, 2, 3, 4, 5, _and_ 500):
```
NetworkUpdate(3, 500, -1, <host name='vm-8029d8c8-ee6c-45b9-6476-3ba7381c3cb5' ip='192.168.123.7'/>, 0)
panic: Operation not supported: can't update 'ip' section of network 'default'
```
I am using Go 1.12 and modules. `go.mod` is:
```
$ cat go.mod
module ip-dhcp-host

go 1.12

require github.com/digitalocean/go-libvirt v0.0.0-20190715144809-7b622097a793
```
Just in case there's a specific version or something.

**Comment by a2geek** [comment]
Hmm. Going with your suggestion, I "widened" the net... I tried setting command, section, _and_ flags to 4.  Flags wouldn't allow it (actually gave me a flags related error).

But...
```
	cmd := uint32(4)
	section := uint32(4)
	fmt.Printf("NetworkUpdate(%d, %d, -1, %s, %d)\n", cmd, section, networkDhcpXML, 0)
	err = client.NetworkUpdate(net, cmd, section, -1, networkDhcpXML, 0)
```

Gave me:
```
NetworkUpdate(4, 4, -1, <host name='vm-8029d8c8-ee6c-45b9-6476-3ba7381c3cb5' ip='192.168.123.7'/>, 0)
Setup network DHCP
```

... and as proof:
```
$ virsh net-dumpxml default
<network>
  <name>default</name>
  <uuid>bcb85dc8-ad27-4861-9f85-692167fd79fa</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr0' stp='on' delay='0'/>
  <mac address='52:54:00:82:d1:6e'/>
  <ip address='192.168.123.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.123.2' end='192.168.123.254'/>
      <host name='vm-8029d8c8-ee6c-45b9-6476-3ba7381c3cb5' ip='192.168.123.7'/>
      <host name='totally-fake-vm' ip='192.168.123.6'/>
    </dhcp>
  </ip>
</network>
```

... and running it again errors out (as expected):
```
NetworkUpdate(4, 4, -1, <host name='vm-8029d8c8-ee6c-45b9-6476-3ba7381c3cb5' ip='192.168.123.7'/>, 0)
panic: Requested operation is not valid: there is an existing dhcp host entry in network 'default' that matches "<host mac='unknown' name='vm-8029d8c8-ee6c-45b9-6476-3ba7381c3cb5' ip='192.168.123.7'/>"
```

Is something cross-wired somewhere? Even in my code? Sadly, I'm not spotting anything. (But also admitting I'm a Go rookie, haven't touched C in 30 years, and utter neophyte with Libvirt! LOL)

**Comment by kskewes** [comment]
Thank you so much for posting this issue. We've just run into it with the terraform libvirt provider.

Seems there has been work going on upstream to improve a situation where `command` and `section` argument ordering is swapped around.

See:
- v1 fix (not merged) https://listman.redhat.com/archives/libvir-list/2021-March/msg00054.html
- v2 fix (merged) https://listman.redhat.com/archives/libvir-list/2021-March/msg00758.html
