### ISSUE TITLE
cannot acquire state change lock

### ISSUE THREAD

**Issue by fcddk** [digitalocean/go-libvirt#90]
failed to get DomainBlockStats: Timed out during operation: cannot acquire state change lock (held by remoteDispatchDomainBlockStats)

my code:

`		
		
`isActive, err := l.DomainIsActive(*domain)`
		`var rRdReq, rRdBytes, rWrReq, rWrBytes int64`
		`if isActive == 1 {`
			`rRdReq, rRdBytes, rWrReq, rWrBytes, _, err = l.DomainBlockStats(*domain, `disk.Target.Device)`
		`}`

		if err != nil {
			log.Fatalf("failed to get DomainBlockStats: %v", err)
			return err
		}
`

**Comment by fcddk** [comment]
What causes this error?

**Comment by trapgate** [comment]
It's a bug in libvirt, or possibly in qemu, I believe. We see this occasionally too - it's possible for a libvirt domain to get into this state where something is holding the state change lock (the state change locks are implemented by libvirt), and never releases it.

When this happens its not just go-libvirt that's affected - running `virsh` commands on the domain will produce the same error.

**Comment by fcddk** [comment]
Any better suggestions? solve this problem.

**Comment by benlemasurier** [comment]
As @trapgate mentioned, this is not an issue within go-libvirt.
