### ISSUE TITLE
use of closed network connection

### ISSUE THREAD

**Issue by fcddk** [digitalocean/go-libvirt#91]
DomainGetXMLDesc: write unix @->/var/run/libvirt/libvirt-sock: use of closed network connection.

code:
	xmlDesc, err := l.DomainGetXMLDesc(*domain, 0)
	if err != nil {
		log.Printf("failed to DomainGetXMLDesc: %v", err)
		return err
	}

**Comment by fcddk** [comment]
libvirt service is running normally.

**Comment by vtolstov** [comment]
can you provide full example? i don't see such error
