### ISSUE TITLE
DomainGetCPUStats param

### ISSUE THREAD

**Issue by fcddk** [digitalocean/go-libvirt#92]
// DomainGetCPUStats is the go wrapper for REMOTE_PROC_DOMAIN_GET_CPU_STATS.
func (l *Libvirt) DomainGetCPUStats(Dom Domain, Nparams uint32, StartCPU int32, Ncpus uint32, Flags TypedParameterFlags) (rParams []TypedParam, rNparams int32, err error) {
}
Nparams ，StartCPU，TypedParameterFlags
How to finish the above three parameters?
And What can I get back?  rParams ，rNparams

**Comment by trapgate** [comment]
I'm not sure what you're asking here. If you're looking for help decoding the returned TypedParams, check in libvirt.go, there are some examples there that show how it's done. The returned rNparams value is redundant - `len(rParams)` will tell you the same thing..

**Comment by fcddk** [comment]
Nparams ，StartCPU，TypedParameterFlags
How to finish the above three request parameters?

**Comment by fcddk** [comment]
I don’t understand the meaning of these three parameters。

**Comment by trapgate** [comment]
Your best resource for that question is the libvirt documentation for this function, which is here: https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainGetCPUStats

**Comment by fcddk** [comment]
resultSli, _, err := l.DomainGetCPUStats(*domain, 1, -1, 1, 0)
	if err != nil {
		log.Printf("failed to get domainCpuState: %v", err)
		return err
	}
	for _, value := range resultSli {
		fmt.Printf("cpuState: %v", value)
	}

**Comment by fcddk** [comment]
return:
cpuState: {cpu_time {4 1740335852754}}
cpuState: {cpu_time {4 663492372092}}
cpuState: {cpu_time {4 2788674600845}}
cpuState: {cpu_time {4 7265418187967}}
cpuState: {cpu_time {4 62431433010}}
cpuState: {cpu_time {4 20751254614}}
cpuState: {cpu_time {4 596372260237}}
cpuState: {cpu_time {4 233139094885}}

**Comment by fcddk** [comment]
How does the data returned by the interface help me calculate CPU usage?

**Comment by vtolstov** [comment]
You must take two measurements.
After that substract from second measure first. Divide by number of seconds between two measurements.
Also note that stats for each cpu. So if you need total sum.
