### ISSUE TITLE
DomainGetInfo interface always return inaccurate data

### ISSUE THREAD

**Issue by fcddk** [digitalocean/go-libvirt#95]
rState, rmaxmem, rmemory, rvirCpu, rcputime, err := l.DomainGetInfo(*domain)

rmaxmem and  rmemory are always equal.

**Comment by trapgate** [comment]
What makes you think this is an error? You can display this information with `virsh dominfo` as well, and I think you'll find the values are the same.

**Comment by fcddk** [comment]
Really so.
Libvirt is too weak!!!!!!!
