### ISSUE TITLE
Libvirt locks on `getResponse()`

### ISSUE THREAD

**Issue by dshemin** [digitalocean/go-libvirt#96]
Hi,

I have some goroutines:
* One for listening and processing domain lifecycle events. Call `DomainGetState` for each domain from event;
* Multiple for handling start/stop VM's and wait until state become to required sequentially call `DomainGetState`;
* One for collecting and processing metrics for every domains. Use `DomainBlockStats`, `DomainInterfaceStats` and etc. function for collecting metrics.

I faced with an next issue: sometimes, when I request to start or stop multiple domain at once, all those goroutines is stuck. I try to dig into this issue and find out that all goroutines is blocked on `digitalocean/go-libvirt.Libvirt.getResponse()` because cannot read message from channel. Unfortunately this is a floating bug and I cannot find how to reproduce it.

For now I use this workaround:

```
const getResponseTimeout = 5 * time.Second

func (l *Libvirt) getResponse(c chan response) (response, error) {
	timer := time.NewTimer(getResponseTimeout)
	defer timer.Stop()

	var resp response
	select {
	case <-timer.C:
		return response{}, fmt.Errorf("cannot get response from libvirt within %s", getResponseTimeout)
	case resp = <-c:
	}
	if resp.Status == StatusError {
		return resp, decodeError(resp.Payload)
	}

	return resp, nil
}
```

Anyone have some thoughts why this happens?

**Comment by trapgate** [comment]
When this happens, is libvirt still responsive to `virsh` commands? Virsh uses the same rpc interface to talk to libvirt that go-libvirt uses, so if virsh also becomes unresponsive it would point to a problem in libvirt itself.

**Comment by freedemster** [comment]
Yes, it still responsive. I can call any `virsh` commands and they work correctly.

**Comment by vtolstov** [comment]
when it fails again , can you try to dump all goroutines stack and share it with this issue?
Also can you try to compile you code (that sometimes fails like you say) with race detector?

**Comment by freedemster** [comment]
Yes, I compile my code with race detector and don't get any panics when it stuck, so it's not a race condition in my code (I hope :smile:).
Attach archive with:
- trace
- cpu profile
- mutex profile
- goroutine profile

[2020-01-14-02-17-35.zip](https://github.com/digitalocean/go-libvirt/files/4077076/2020-01-14-02-17-35.zip)

**Comment by vtolstov** [comment]
i mean something different:
when you app if stuck and locks send to it SIGABRT so it prints to stderr all goroutine stack present on moment when you sent signal

**Comment by freedemster** [comment]
Ok, I will try to reproduce and dump goroutines.

**Comment by freedemster** [comment]
Goroutines dump in attached file.
[goroutines.txt](https://github.com/digitalocean/go-libvirt/files/4184948/goroutines.txt)

**Comment by vtolstov** [comment]
thanks, how much vm i can ran to may be reproduce this issue? 50 is enough?

**Comment by freedemster** [comment]
We reproduce this bug with 5 VMs. The main thing that all operations should perform in parallel.

**Comment by WanLinghao** [comment]
https://github.com/digitalocean/go-libvirt/pull/98 fix this

**Comment by dshemin** [comment]
Looks like we found why we got a random hang on libvirt connection. We use the same connection for sending commands and for receiving events. And we got an idea that this is a key to the problem. So now we use two different connections. One is read-only for events and second for the commands and everything looks good.
